language: php

# TODO: figure out how to not use apt-get
#sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - mysql

php:
  - 5.5

env:
  - WP_VERSION=4.3.1 WP_MULTISITE=1

before_install:
  # - sudo apt-get update
  # - gem update --system
  - cd .standards
  - composer install
  - ./vendor/bin/phpcs -vvv -w --config-set installed_paths "../../../coding_standards/"
  - cd ../
  - bash ./bin/dep.sh
  - gem update --system
before_script:
  # For your convenience:
  # sudo mysqladmin drop -f wordpress_test --user="root" --password="root"
  # sudo bash bin/install-wp-tests.sh wordpress_test root 'root' localhost 4.0.1
  - sudo bash bin/install-wp-tests.sh wordpress_test travis '' localhost $WP_VERSION
  - cd .standards

script:
  - grunt
